In [75]:
# Import Liabrary 
import pandas as pd
import re
import spacy
nlp = spacy.load("en_core_web_sm")

In [76]:
# Load the CSV files
df1 = pd.read_csv("data/collegereview2021.csv")
df2 = pd.read_csv("data/collegereview2022.csv")

In [77]:
# concat the data
df = pd.concat([df1, df2], ignore_index=True)
df.head()

,Unnamed: 0,Name,college,review,rating
0,0,Nimalraj,SNS College of Technology - [SNSCT],"The annual fee for the course is 1,25,000. Now...",6.0
1,1,Priyaranjan kumar,Bhagalpur College of Engineering - [BCE],The hostel life and social life in this colleg...,9.7
2,2,Aftab Shaikh,Shree LR Tiwari College of Engineering - [SLRTCE],I chose this course because I was interested i...,8.0
3,3,Shreya sneh,IILM University,There is IGNITE fest in the university held on...,10.0
4,4,Yuv Raj Singh,Galgotias University - [GU],The civil department is very good in this coll...,6.2

In [78]:
# Shape
df.shape

(28076, 5)

In [79]:
df.columns

Index(['Unnamed: 0', 'Name', 'college', 'review', 'rating'], dtype='object')

In [80]:
# Delete unnecessary columns
# 'Unnamed: 0' and 'Name' will not help model. so removing it
df = df.drop(["Unnamed: 0", "Name"], axis=1)

In [81]:
df.head()

,college,review,rating
0,SNS College of Technology - [SNSCT],"The annual fee for the course is 1,25,000. Now...",6.0
1,Bhagalpur College of Engineering - [BCE],The hostel life and social life in this colleg...,9.7
2,Shree LR Tiwari College of Engineering - [SLRTCE],I chose this course because I was interested i...,8.0
3,IILM University,There is IGNITE fest in the university held on...,10.0
4,Galgotias University - [GU],The civil department is very good in this coll...,6.2

In [82]:
# making college name lowercase
df["college"] = df["college"].str.strip().str.lower()

In [83]:
df.sample(5)

,college,review,rating
14704,smt. p.n. doshi women's college,The college arranges many functions and compet...,8.0
3062,iit delhi - indian institute of technology [iitd],IIT Delhi attracts the attention of the best r...,8.3
11010,sri venkateshwara college of engineering - [svce],Campus life is busy but also very fun with the...,7.4
26480,college of engineering trikaripur,1)IEEE\n2)ISTE\n3)NSS(national service scheme)...,7.0
6022,vallurupalli nageswara rao vignana jyothi inst...,"I choose EEE because I am interested in EEE, f...",10.0

In [84]:
# making review lowercase
df["review"] = df["review"].str.strip().str.lower()

In [85]:
df.sample(5)

,college,review,rating
20425,lovely professional university - [lpu],i choose b.tech compressions in engineering wi...,6.7
25969,pravara rural engineering college - [prec] loni,i choose the civil engineering department beca...,9.2
12144,anil neerukonda institute of technology & scie...,the fee structure is somewhat convincing for t...,6.8
23843,rvr and jc college of engineering,our college follows the most updated syllabus....,7.7
2751,kln college of engineering - [klnce],from the 6th semester onwards we are eligible ...,8.5

In [86]:
# DATA CLEANING

In [87]:
print("Rating is NaN:", df["rating"].isna().sum())
print("Empty reviews:", (df["review"].isna() | (df["review"].str.strip() == "")).sum())
df.shape

Rating is NaN: 105
Empty reviews: 81

(28076, 3)

In [88]:
# we have a lerge dataset , can remove rows with raing NAN
df = df.dropna(subset=["rating"])

In [89]:
# we have a lerge dataset , can remove empty and nan reviews
df = df[~(df["review"].isna() | (df["review"].str.strip() == ""))]

In [90]:
print("Rating is NaN:", df["rating"].isna().sum())
print("Empty reviews:", (df["review"].isna() | (df["review"].str.strip() == "")).sum())
df.shape

Rating is NaN: 0
Empty reviews: 0

(27971, 3)

In [91]:
# FEARURE ENGINEERING

In [92]:
# Dataset do't have label

In [93]:
# Apply labeling
df["label"] = 0

In [94]:
df.head()
# Label = 1 → Fake
# Label = 0 → Genuine

,college,review,rating,label
0,sns college of technology - [snsct],"the annual fee for the course is 1,25,000. now...",6.0,0
1,bhagalpur college of engineering - [bce],the hostel life and social life in this colleg...,9.7,0
2,shree lr tiwari college of engineering - [slrtce],i chose this course because i was interested i...,8.0,0
3,iilm university,there is ignite fest in the university held on...,10.0,0
4,galgotias university - [gu],the civil department is very good in this coll...,6.2,0

In [95]:
df = df.reset_index(drop=True)

In [96]:
print("Label = 0:", (df["label"] == 0).sum())
print("Label = 1:", (df["label"] == 1).sum())

Label = 0: 27971
Label = 1: 0

In [97]:
df["label"].value_counts()

label
0    27971
Name: count, dtype: int64

In [98]:
# I augmented the dataset by generating synthetic deceptive 
# reviews based on common linguistic patterns observed in fake reviews.

In [99]:
df3 = pd.read_csv("data/fake_reviews.csv")

In [100]:
df3.head()

,Name,college,review,rating,label
0,Brijesh Kumar,ISM Dhanbad - Indian Institute of Technology -...,The fee structure is available at the official...,5,1
1,Chandrakumar,Potti Sriramulu College of Engineering and Tec...,Written ecet exam and attended for the web cou...,5,1
2,Akash Kumar Jaiswal,Lakshmi Narain College of Technology & Science...,"Recently in April culture fest is held named ""...",5,1
3,Pagidi reddy Varun sai reddy,JNTUA College of Engineering,The course curriculum is excellent but not per...,5,1
4,Sakshi Borse,Sandip Institute of Engineering and Management...,As a student of Sandip Institute of Engineerin...,5,1

In [101]:
# Delete Name Column
df3 = df3.drop(["Name"], axis=1)

In [102]:
df = pd.concat([df, df3], ignore_index=True)

In [103]:
df.sample(5)

,college,review,rating,label
28508,JSS Academy of Technical Education - [JSSATE],I am interested in this course because as the ...,5.0,1
34867,Netaji Subhas University of Technology - [NSUT],Fees for 1 year are nearly Rs219000. There are...,5.0,1
1036,madhav institute of technology and science - [...,i used to spend my time on the college campus ...,7.7,0
8682,amity university,college life is good and amity university raip...,6.7,0
7396,gitam,there are many festa conducted at the college ...,8.4,0

In [104]:
print("Label = 0:", (df["label"] == 0).sum())
print("Label = 1:", (df["label"] == 1).sum())
df.shape

Label = 0: 27971
Label = 1: 12032

(40003, 4)

In [105]:
df.to_csv("data/labeled_reviews.csv", index=True)

In [106]:
# DATA PRE-PROCESSING

In [107]:
# We have spacy
# This function performs: Tokenization, Stopword removal, Punctuation removal, Lemmatization

def preprocess_text(text):
    doc = nlp(str(text).lower())
    
    tokens = []
    
    for token in doc:
        # remove stopwords, punctuation, spaces
        if token.is_stop:
            continue
        
        if token.is_punct:
            continue
        
        if token.is_space:
            continue
        
        # keep only alphabetic words
        if not token.is_alpha:
            continue
        
        # lemma
        tokens.append(token.lemma_)
    
    return " ".join(tokens)

In [108]:
# Apply Pre-preocessing

In [109]:
df["processed_review"] = df["review"].apply(preprocess_text)

In [110]:
df.head()

,college,review,rating,label,processed_review
0,sns college of technology - [snsct],"the annual fee for the course is 1,25,000. now...",6.0,0,annual fee course force pay fee early total bo...
1,bhagalpur college of engineering - [bce],the hostel life and social life in this colleg...,9.7,0,hostel life social life college enjoyable club...
2,shree lr tiwari college of engineering - [slrtce],i chose this course because i was interested i...,8.0,0,choose course interested mechanical engineerin...
3,iilm university,there is ignite fest in the university held on...,10.0,0,ignite f university hold campus availability j...
4,galgotias university - [gu],the civil department is very good in this coll...,6.2,0,civil department good college faculty member g...

In [111]:
# save pre-processed dataset
df.to_csv("data/processed_reviews.csv", index=False)